services:
  - type: web
    name: skin-disease-detection
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --workers 1 --threads 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.9

