services:
  - type: web
    name: skin-disease-detection
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --workers 1 --threads 2 --timeout 180
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"


